services:
  flood:
    hostname: flood
    image: jesec/flood
    container_name: flood
    user: 1000:1001
    restart: unless-stopped
    command: --port 3002 --allowedpath /data/downloads/qbittorrent
    volumes:
      - /docker/FloodUI/config:/config
      - /data/downloads/qbittorrent:/data
    ports:
      - 0.0.0.0:3002:3002
