services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
     - "8096:8096" # http
    volumes:
     - /docker/jellyfin/config:/config
     - /data:/media # media sorting is managed in jellyfin during setup
    environment:
     - JELLYFIN_PublishedServerUrl=http://example.com # used for autodiscovery
    restart: unless-stopped