services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /docker/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - /docker/jellyfin/stats/postgres:/var/lib/postgresql/data

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: "a_random_secret"
      TZ: America/Halifax
    volumes:
      - /docker/jellyfin/stats/backup-data:/app/backend/backup-data
    ports:
      - "3000:3000"
    depends_on:
      - jellystat-db

  streamystats:
    image: fredrikburmester/streamystats-nextjs:edge
    ports:
      - "3001:3000"
    depends_on:
      - phoenix
    networks:
      - backend
    environment:
      API_URL: "http://phoenix:4000/api"
      TZ: "America/Halifax"

  phoenix:
    image: fredrikburmester/streamystats-phoenix:edge
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/streamystat"
      SECRET_KEY_BASE: "r0NgGxu5ETTDgF5G7mJsMevMbAF7y4w0IJlCRjzxHqSjbcrPqTQTzajOH0ne0sHH"
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - backend

  streamydb:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "none"

volumes:
  pgdata:

networks:
  backend: