services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=America/Halifax
      - UMASK_SET=002
      - serverIP=<host-ip>
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=MyInternalNode # Can be changed to whatever you want
    volumes:
      - /docker/tdarr/server:/app/server
      - /docker/tdarr/config:/app/configs
      - /docker/tdarr/logs:/app/logs
      - /data:/media # where the media files are
      - /docker/tdarr/transcode_cache:/temp
    devices:
      - '/dev/dri:/dev/dri' # Intel QSV passthrough
