services:
  panel:
    image: derkades/dockerpanel
    ports: ['8080:80']
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    environment:
      CONTAINERS: <container_name container_name container_name> # Formatting to show containers.
      # For a list of themes have a look at https://github.com/Derkades/dockerpanel/tree/master/themes
      THEME: black
    restart: unless-stopped
