services:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=86400
      # - WATCHTOWER_NOTIFICATIONS=shoutrrr # Uncomment both lines to use notifications
      # - WATCHTOWER_NOTIFICATION_WEBHOOK= # Discord Webhook or other
